fix for comparing scaled vs unscaled difficulty
mimblewimble/grin pull request #3624
Opened 2021-03-27 19:43 UTC by bladedoyle

Fix for compare of scaled and unscaled difficulty.

2021-03-29 20:57 UTC, phyro commented
@quentinlesceller I suspect you might be appropriate for the stratum changes, but I can't assign you 👀

2021-03-31 20:54 UTC, tromp reviewed
Instead of all those changes, isn't it simpler to scale up minimum_share_difficulty by the minimum graph weight (of C32) ?
That has the same behaviour, and doesn't require computing scaled_share_difficulty and unscaled_share_difficulty side by side.

2021-03-31 21:25 UTC, bladedoyle commented
I think we probably want matching scaled and unscaled methods since the rust project can be used by upstream devs as a library.  From personal experience (rust stratum server links to grin library for POW methods) I am certain that people look for it and are confused when no method exists.  If you already know the technical details about what scaling is and how to calculate it it seems like a trivial point.  But if you dont know the details and the method does not exist that makes things much harder.  I would like to leave the method if you dont object too strongly?

2021-03-31 21:56 UTC, tromp commented
Ok, if you think it's useful. But I don't like the separate from_proof_unscaled. Can you just inline it into  to_unscaled_difficulty ?

2021-04-03 20:51 UTC, bladedoyle commented
Sure, let me take a look at your suggestion and adjust the PR.  I hope to find time in the next few days.

2021-04-15 01:26 UTC, bladedoyle commented
@tromp Can you take another look to make sure I understood your request correctly.

2021-04-15 15:15 UTC, tromp commented on core/src/pow/types.rs
> +		Difficulty::from_num(self.proof.scaled_difficulty(1 as u64))
We write this simply as 1u64

2021-04-15 15:24 UTC, tromp requested changes
Looks ok, with the suggested change in u64 literal notation.
The release this is going into should make clear that this affects miners who have set a minimum share difficulty greater than the default 1.

2021-04-15 16:21 UTC, bladedoyle commented
@tromp Ok.  This config item was always intended to be unscaled value, so this is a bug fix.  But I do agree that it should be mentioned in the release notes in case people were using the scaled value there.

@quentinlesceller Can you please give a second review and merge if you agree with the changes?

2021-04-15 16:22 UTC, phyro commented
We seem to show PR titles in https://github.com/mimblewimble/grin/releases. Should we introduce at some point some form of a changelog? e.g. https://github.com/mitsuhiko/redis-rs/blob/master/CHANGELOG.md

2021-04-16 01:20 UTC, bladedoyle commented
I updated the PR title to be a more descriptive changes log entry

2021-04-22 17:57 UTC, quentinlesceller approved these changes
Looking good to me 👍

2021-04-22 19:11 UTC, phyro commented
@tromp you still have "requested changes" on this one. I'm not sure whether this blocks the merge or not, but I'm assuming it's a :+1: from you as well now?

2021-04-22 20:19 UTC, tromp approved these changes

2021-04-22 20:20 UTC, tromp approved these changes

2021-04-22 20:21 UTC, tromp approved these changes

2021-04-23 13:28 UTC, merged